### DISCUSSION TITLE
Use of the Event APIs listed in content-api/content-service/conf/routes

### DISCUSSION THREAD

**Discussion by vaivk369** [Sunbird-Knowlg/Community#192] [General Discussions]
Hi,

In the [repository](https://github.com/Sunbird-Knowlg/knowledge-platform/blob/release-6.0.0), I see the Event and Eventset APIs listed, but I am not able to trigger those APIs. It seems the APIs are not on-boarded. 

We need to create online events and add it as part of a course/collection.
It will be great if someone could assist us here.

@AmiableAnil @krgauraw @pallakartheekreddy

**Comment by vaivk369** [comment]
Can we please get some help here?

**Reply by pallakartheekreddy** [reply]
@vaivk369 The Event and EventSet APIs are considered optional, and by default, they are not included in our onboarded APIs. However, any adopter has the option to onboard these APIs by referring to the documentation provided below.
https://project-sunbird.atlassian.net/wiki/spaces/DevOps/pages/1205207131/Best+Practces+For+Onboarding+API+s+In+Sunbird

**Reply by vaivk369** [reply]
Thank you @pallakartheekreddy. We will check this.

**Reply by komalm** [reply]
Hello @pallakartheekreddy,


I am reaching out to inform you about an issue we are currently experiencing with the Publish API integration. Despite following the provided document, we have encountered difficulties in getting the Publish API to function properly.

**Here are the details of our attempts:**

We have successfully onboarded and tested the following APIs:

1. Create Event
2. Update Event
3. Read Event

However, when attempting to integrate the **Publish API**, we encountered a **404 error response for both upstream URLs**:

```
"{{ vm_learning_service_url }}/event/v4/publish"
"{{ knowledge_mw_service_url }}/event/v4/publish"
```

We have tried using both upstream URLs, but unfortunately, neither has resolved the issue.

**Below is the code snippet we've implemented for reference:**

```
- name: EventPublishAPI
  uris: "{{ event_prefix }}/v4/publish"
  upstream_url: "{{ vm_learning_service_url }}/event/v4/publish"
  strip_uri: true
  plugins:
  - name: jwt
  - name: cors
  - "{{ statsd_pulgin }}"
  - name: acl
    config.whitelist:
    - contentCreate
  - name: rate-limiting
    config.policy: local
    config.hour: "{{ medium_rate_limit_per_hour }}"
    config.limit_by: credential
  - name: request-size-limiting
    config.allowed_payload_size: "{{ small_request_size_limit }}"
  - name: opa-checks
    config.required: false
    config.enabled: false
```

Could you please assist us in troubleshooting and resolving this issue with the Publish API integration? Any guidance or support you can provide would be greatly appreciated.

Thank you for your attention to this matter.
 
 cc @vaivk369, @siddhishinde0723
